"""Добавлены balance и hold_balance для User

Revision ID: f8f582b92c78
Revises: caec1884e60c
Create Date: 2025-04-12 09:19:22.055021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f582b92c78'
down_revision = 'caec1884e60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hold_balance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot', schema=None) as batch_op:
        batch_op.drop_column('hold_balance')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
